# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. 
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Stephanie's Coding Adventures
email: stephaniescodingadventure@gmail.com
description: Hi, I'm Stephanie. Software developer. Blogger. Macaron connoisseur. Adventurer. Traveller. Believer in living life to the full.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stephaniescodingadventures.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: stephanie_code
github_username:  stephanieM89
repository: "stephanieM89/stephanieM89.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

[params.comments.staticman]
enable = true
apiEndpoint = "https://dev.staticman.net/v3/entry/github"
maxDepth = 2


[params.comments.staticman.github]
username = "stephanieM89"
repository = "stephanieM89.github.io"
branch = "master"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


